### PR TITLE
feat: Rewrite of the bot in golang

### PR DESCRIPTION
**Pull request by vleeuwenmenno**
New features in this PR are:

- [x] Configurable services instead of hardcoded
- [x] Web portal for changing settings of the bot for admins and members
- [x] Health monitoring for the container
- [x] Better user level configuration using a menu based system
- [x] Better performance due to GoLang
- [x] Feature parity with the old C# version of the bot
- [x] CI Improvements
- [x] More rigid settings persistence

Maybe features?:
- [x] WONT DO Spotify embeds on card instead of keeping original messages
    - Sadly it looks like we can't pass over the embeds from Spotify because this is fully custom made for them by Discord https://www.reddit.com/r/discordapp/comments/x2ikck/new_spotify_embeds/
- [x] Direct links to streaming services on the cards (WONT DO for now, I will need to find a way for this without causing issues with the author of Songwhip)

Settings:
- [x] Option to keep original message
- [x] Option to toggle auto resolving for music links
- [x] Options for the admin on the web portal to disable / enable user overrides per setting. (This allows the admin to disallow/allow people to change their personal preference, for example auto-resolving.)

### CODE REVIEW

**Comment by vleeuwenmenno** [comment]
Sneak peak, 
image

**Comment by nobuhojimichaan** [comment]
thanks for these updates @vleeuwenmenno '   how do we access the web portal for admin ? '   i looked at the README.md but didn't find anything and i didn't wanna look thru the PR yet '

**Comment by vleeuwenmenno** [comment]
Yeah, I should add some more documentation for this. 

You can use the command `/settings` to get a link, and this also includes admin settings if you have the admin role. 

The admin role is made when the bot starts up or is added to your server. But the bot needs that permission, so make sure you re-add the bot if it doesn't have the permission yet.

**Comment by vleeuwenmenno** [comment]
For reference 
image

**Comment by vleeuwenmenno** [comment]
@nobuhojimichaan https://github.com/vleeuwenmenno/songwhip-bot/pull/32 does this suffice for your questions?

**Comment by nobuhojimichaan** [comment]
> @nobuhojimichaan https://github.com/vleeuwenmenno/songwhip-bot/pull/32 does this suffice for your questions?

thank u ' i tried it out and i have not felt moved to play around with it yet or investigate the admin / non-admin functionality ' but u have answered my questions very well ' thank u again and thank u again for ur work ! '

**Pull request merged**
